apiVersion: apps/v1
kind: Deployment
metadata:
  name: caching-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caching-service
  template:
    metadata:
      labels:
        app: caching-service
    spec:
      containers:
      - name: caching-service
        image: caching-service:latest
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: caching-service
spec:
  selector:
    app: caching-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
